### ISSUE TITLE
periodically request to siterm

### ISSUE THREAD

**Issue by sunami09** [esnet/sense-rtmon#105]
There are 2 ways we can do it.
1. Statically: Save time and the data we pushed in map. And then when it reaches 6 hrs we push the data again and update the map with time and ID.
2. Dynamic: We use the GET method to see whether it's still alive or not and push it if its not.

**Comment by sunami09** [comment]
The dashboard shows some data: http://dev2.virnao.com:3000/d/ddlzz7ne4s0zka/620ff10b-6283-5ba3-af3f-0fb52d5a90e9?orgId=1

**Comment by PannuMuthu** [comment]
Thanks @sunami09! Investigating the dashboard panels, looks like the queries are updated (i.e. no underscore in Port-channel as we are using the true iface name rather than the URL alias) so stepping through the panels which have no data we can see:

---
**dellos10_s0 Switch Panel:**

 
<img width="1216" alt="missingPanel" src="https://github.com/esnet/sense-rtmon/assets/30813477/e04d864b-2fef-48c5-85bf-8399f6a0a1c1">

<img width="808" alt="Screen Shot 2024-05-17 at 10 55 53 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/27b4389c-3a66-43eb-8e4b-86e66bc34aad">

Taking a closer look at the Pushgateway jobs page:

<img width="1455" alt="Screen Shot 2024-05-17 at 10 54 30 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/79be63ec-7e57-4f40-879c-d66e4afaa706">

We can see that Site-RM job for `dellos10_s0` is not showing, so potentially SiteRM is not configured on this switch to export SNMP metrics. Further, the metrics page shows that Pushgateway is not scraping SNMP metrics from this switch.

---

**oasis Switch Panel:**

<img width="1222" alt="Screen Shot 2024-05-17 at 10 57 51 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/d3f2e18a-7b74-40e3-bdba-5971074acb55">

<img width="827" alt="Screen Shot 2024-05-17 at 10 58 17 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/4b6bdba3-3277-4d65-a57e-915e1b05734a">

Looking at the Pushgateway jobs page:

<img width="1455" alt="Screen Shot 2024-05-17 at 10 54 30 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/79be63ec-7e57-4f40-879c-d66e4afaa706">

We can also see that Site-RM job for `oasis` is not showing, so potentially SiteRM is not configured on this switch to export SNMP metrics. Further, the metrics page shows that Pushgateway is also not scraping SNMP metrics from this switch.

---

**L2 Debugging ARP Exporter Active Status: `dellos10_s0` and `oasis`**

Looking at ARP exporter active status for `dellos10_s0` and `oasis`, we can see that the dashboard correctly identifies ARP / SNMP Exporter as inactive for these switches, which correlates with what we saw in Pushgateway / Prometheus metrics.

<img width="1234" alt="Screen Shot 2024-05-17 at 10 59 22 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/0908f0ee-dbba-4010-806c-e324b3bdb5b9">

---

**L2 Debugging ARP Exporter: `sandie-7.ultralight.org`**

Looking at ARP exporter active status for the `sandie-7.ultralight.org` host, we can see that it shows up as active, but there is no ARP entry for the host.

<img width="1222" alt="Screen Shot 2024-05-17 at 11 00 33 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/8bb18623-98d3-4e77-8e44-44c4bade71b3">

Taking a look at the flow topology, we can see that this is expected behavior:

<img width="1219" alt="Screen Shot 2024-05-17 at 11 02 34 AM" src="https://github.com/esnet/sense-rtmon/assets/30813477/d1f675eb-a964-42e5-8d2b-6d2754e0e332">

---

**Conclusion:** Grafana queries are formatted correctly and we are seeing expected behavior in this dashboard, where we see data when data is available and we see notifications of missing data when SiteRM is not exporting metrics or data is unavailable.

**Comment by juztas** [comment]
put a label under-review - still need to think if we want to go that path of prometheus push. It does include more complexity and security issues - like secure endpoint, auth/authz.

**Comment by juztas** [comment]
Closing. All lives under autogole and no need for now prom push (maybe in future)
