### ISSUE TITLE
Run Update Script

### ISSUE THREAD

**Issue by sunami09** [esnet/sense-rtmon#73]
### Description

While attempting to run the `update.sh` script to update our environment and Docker images, we encountered several issues related to missing files and errors during the Docker build process. The script aims to copy certain files, build a Docker container, and clean up afterward. However, missing files and Docker build errors prevent the script from completing successfully.

### Steps to Reproduce

1. Run `./update.sh` from the terminal.

### Expected Behavior

The script should successfully copy the required files, build the Docker container, run it, and remove the copied files without errors.

### Actual Behavior

The script failed to find and copy the specified files (`privkey.pem`, `cert.pem`, `.sense-o-auth.yaml`), resulting in errors during the Docker build process. Furthermore, the Docker run command failed due to the non-existence of the `mainloop` image, likely caused by the build process failure.

### Error Output

1. **Copy File Errors**:
    ```plaintext
    cp: cannot stat '/etc/letsencrypt/live/dev2.virnao.com/privkey.pem': No such file or directory
    cp: cannot stat '/etc/letsencrypt/live/dev2.virnao.com/cert.pem': No such file or directory
    cp: cannot stat '/root/.sense-o-auth.yaml': No such file or directory
    ```

2. **Docker Build and Run Errors**:

      ![image](https://github.com/esnet/sense-rtmon/assets/66564001/e084b924-322e-4932-a66d-ea35ca6883cd)

3. **Cleanup Errors**:
    ```plaintext
    rm: cannot remove 'privkey.pem': No such file or directory
    rm: cannot remove 'cert.pem': No such file or directory
    rm: cannot remove '.sense-o-auth.yaml': No such file or directory
    ```

**Comment by PannuMuthu** [comment]
Sunami and I had a meeting on 2/22 to discuss certification issues. Sunami was blocked by the LetsEncrypt certificate auto-generation process being inconfigurable due to no DNS available on the host machine. 

Following this meeting, I used the DuckDNS service to configure a DNS for the host under the DuckDNS subdomain. The configured DNS for this VM is **dev1-host.duckdns.org**


<img width="1296" alt="Screen Shot 2024-02-22 at 9 44 48 PM" src="https://github.com/esnet/sense-rtmon/assets/30813477/c2a88768-9f8a-4d32-a1d4-df3f5c93835d">

After creating the DNS, I was able to generate the LetsEncrypt certificates using the CertBot container by following the install script:

<img width="1115" alt="Screen Shot 2024-02-22 at 9 43 31 PM" src="https://github.com/esnet/sense-rtmon/assets/30813477/c5520280-9b1b-4765-b58b-605bcdecc163">

The certificate and private key are stored in the default path for the VM:

Certificate is saved at: `/etc/letsencrypt/live/dev1-host.duckdns.org/fullchain.pem`
Key is saved at:  `/etc/letsencrypt/live/dev1-host.duckdns.org/privkey.pem`


Expiry: 5-23-2024

**Comment by PannuMuthu** [comment]
Sunami and I had a meeting on 2/22 to discuss certification issues. Sunami was blocked by the LetsEncrypt certificate auto-generation process being inconfigurable due to no DNS available on the host machine. 

Following this meeting, I used the DuckDNS service to configure a DNS for the host under the DuckDNS subdomain. The configured DNS for this VM is **dev1-host.duckdns.org**


<img width="1296" alt="Screen Shot 2024-02-22 at 9 44 48 PM" src="https://github.com/esnet/sense-rtmon/assets/30813477/c2a88768-9f8a-4d32-a1d4-df3f5c93835d">

After creating the DNS, I was able to generate the LetsEncrypt certificates using the CertBot container by following the install script:

<img width="1115" alt="Screen Shot 2024-02-22 at 9 43 31 PM" src="https://github.com/esnet/sense-rtmon/assets/30813477/c5520280-9b1b-4765-b58b-605bcdecc163">

The certificate and private key are stored in the default path for the VM:

Certificate is saved at: `/etc/letsencrypt/live/dev1-host.duckdns.org/fullchain.pem`
Key is saved at:  `/etc/letsencrypt/live/dev1-host.duckdns.org/privkey.pem`


Certificate Expiry: 5-23-2024

I also moved over the SENSE-O authorization YAML to the new VM for use by `./update.sh` in the containerized main loop.

With these changes, we are now able to build the docker container for the main loop on this VM:

<img width="1203" alt="Screen Shot 2024-02-22 at 9 54 18 PM" src="https://github.com/esnet/sense-rtmon/assets/30813477/f7b8268e-bf3a-4685-8330-03f01536a56e">


<img width="1198" alt="Screen Shot 2024-02-22 at 9 54 51 PM" src="https://github.com/esnet/sense-rtmon/assets/30813477/831bec13-f8a7-41e0-a4f3-e17baf7afbef">


The Grafana Server is active under the configured DNS: http://dev1-host.duckdns.org:3000/

<img width="1512" alt="Screen Shot 2024-02-22 at 9 57 43 PM" src="https://github.com/esnet/sense-rtmon/assets/30813477/c28151c8-b306-4c0e-b26d-08ea6557a567">


Containerized main loop successfully generating dashboards:

<img width="780" alt="Screen Shot 2024-02-22 at 9 56 43 PM" src="https://github.com/esnet/sense-rtmon/assets/30813477/4a640654-cb8c-4291-9038-5d8a132e377c">

**Comment by sunami09** [comment]
# Containers
![image](https://github.com/esnet/sense-rtmon/assets/66564001/99a1ce58-5452-4184-a47b-e9d5cf17e5a3)

# URL
![image](https://github.com/esnet/sense-rtmon/assets/66564001/dd600d12-3aa6-4916-89c7-d62c157ecfe7)

# Dashboards 
![image](https://github.com/esnet/sense-rtmon/assets/66564001/7abacce8-dcf9-4031-9e40-b6fae7d94001)

@xi-yang Dashboards are generated in 100.26.56.42 VM.
@xi-yang I think we are ready to test on sense-mon.es.ne : Dashboard Generation.

**Comment by xi-yang** [comment]
great. Let's walk through the install in the Mar 15 meeting.

**Comment by xi-yang** [comment]
dup with #70
